version: "3.7"

services:
  mongodb:
    image: mongo:7
    command: mongod --port 27017
    networks:
      - mi_red
    volumes:
      - mongodb_data:/data/db
      - mongodb_configdb_data:/data/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=HFVHIDL12
      - PUID=1000
      - PGID=1000
    ports:
      - 27017:27017

volumes:
  mongodb_data:
    external: true
    name: mongodb_data
  mongodb_configdb_data:
    external: true
    name: mongodb_configdb_data

networks:
  mi_red:
    external: true
    name: mi_red
